server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  http2:
    enabled: true
  port: 443
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12

spring:
  cloud:
    aws:
      region:
        static: sa-east-1
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      endpoint: https://s3.sa-east-1.amazonaws.com/

  application:
    name: zouk-albums
  datasource:
    url: jdbc:postgresql://localhost:5432/zouk-albums
    username: zoukme.in
    password: s3cr3t
  docker:
    compose:
      lifecycle-management: none
  sql:
    init:
      mode: never

  threads:
    virtual:
      enabled: true
